artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Devesh061102/Dataset_zip/raw/main/Mobile_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/Mobile-data-train.csv
  test_data_path: artifacts/data_ingestion/Mobile-data-test.csv