artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Devesh061102/Dataset_zip/raw/main/Mobile_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/Mobile-data-train.csv
  test_data_path: artifacts/data_ingestion/Mobile-data-test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path : artifacts/data_transformation/train_data.csv
  target_column : price_range
  trained_model_path : artifacts/model_trainer